osx_image: xcode9
language: objective-c
script:
- "xcodebuild -sdk iphonesimulator clean"
- "xcodebuild -workspace EventSource.xcworkspace -scheme EventSource -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test"
- "xcodebuild -workspace EventSource.xcworkspace -scheme EventSourceExample -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' -configuration Release ONLY_ACTIVE_ARCH=NO build"
after_success:
  - bash <(curl -s https://codecov.io/bash)
